### ISSUE TITLE
kernel is not loading 

### ISSUE THREAD

**Issue by Ludea** [kairos-io/kairos#243]
**Kairos version:**

1.1.2
https://github.com/kairos-io/provider-kairos/releases/download/v1.1.2/kairos-alpine-arm-rpi-v1.1.2-k3sv1.25.2+k3s1.img

**CPU architecture, OS, and Version:**

aarch64, alpine flavor

**Describe the bug**

Can't boot on Rpi, get :
```
error: ../../grub-core/disk/loopback.c:98:device name already exists
error: ../../grub-core/loader/arm64/efi/linux.c:59:invalid magic number
error: ../..grub-core/loader/arm64/efi/linux.c:301:you need to load the kernel first
```
**To Reproduce**

Flash img to sd card (following docs) and boot Rpi

**Expected behavior**

Successful boot on Kairos

**Logs**

**Additional context**

**Comment by mudler** [comment]
I'm currently having a look as I have back an rpi4 at my hands. Checking out the repositories configuration currently and seems they are misconfigured and building against 32bit architecture. kudos to @jbalonso for the investigation. I'll follow up from there and check booting issues

**Comment by mudler** [comment]
This should be fixed now, the issue you reported is different from the one from @jbalonso, nevertheless, thanks for opening it up!

**Comment by Ludea** [comment]
Still get issue with https://github.com/kairos-io/provider-kairos/releases/download/v1.1.3/kairos-alpine-arm-rpi-v1.1.3-k3sv1.25.2+k3s1.img
